# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180912_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='app.Grade'),
        ),
    ]
