# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180912_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.AddField(
            model_name='student2',
            name='c',
            field=models.ManyToManyField(null=True, to='app.Course'),
        ),
    ]
